- name: Install productivity tools (fzf, git, tldr, jq)
  homebrew:
    name: ["bash", "fzf", "tldr", "git", "jq", "bc"]
    state: present
    update_homebrew: true
  tags:
    - install
    - productivity
